apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd
  namespace: leafcloud
spec:
  selector:
    matchLabels:
      app: qotd
  template:
    metadata:
      labels:
        app: qotd
    spec:
      containers:
        - name: qotd
          image: dhrp/qotd
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: "/mnt/testvol"
              name: testvol
      volumes:
        - name: testvol
          persistentVolumeClaim:
            claimName: mypvc
