apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: leafcloud
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # storageClassName: csi-cinder-sc-delete
