heat_template_version: queens

resources:
  k8s-1.19.12:
    type: magnum_base_template.yaml
    properties:
      master_lb_enabled: False
      floating_ip_enabled: True
      cluster_template_name: heat-k8s-1.19.12
      kube_tag: v1.19.12
      cloud_provider_tag: v1.19.2

  k8s-1.20.8:
    type: magnum_base_template.yaml
    properties:
      master_lb_enabled: False
      floating_ip_enabled: True
      cluster_template_name: heat-k8s-1.20.8
      kube_tag: v1.20.8
      cloud_provider_tag: v1.20.2
      cinder_csi_plugin_tag: v1.20.3

  k8s-1.21:
    type: magnum_base_template.yaml
    properties:
      master_flavor: cn1.small
      flavor: ec1.medium
      master_lb_enabled: False
      floating_ip_enabled: True
      cluster_template_name: heat-k8s-1.21
      kube_tag: v1.21.2
      cloud_provider_tag: v1.20.2

  k8s-1.21-HA:
    type: magnum_base_template.yaml
    properties:
      master_flavor: cn1.medium
      flavor: ec1.medium
      master_lb_enabled: True
      floating_ip_enabled: False
      cluster_template_name: heat-k8s-1.21-HA
      kube_tag: v1.21.2
      cloud_provider_tag: v1.20.2
